version: '2'

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    shadow: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  revive:
    rules:
      - name: exported
        arguments: ['checkPrivateReceivers', 'sayRepetitiveInsteadOfStutters']

  gocyclo:
    min-complexity: 10

  gocognit:
    min-complexity: 10

  misspell:
    locale: US

  lll:
    line-length: 120

  goimports:
    local-prefixes: mybeerlog

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  funlen:
    lines: 60
    statements: 40

  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - 'strings.SplitN'

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gocognit
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocyclo
        - gocognit

    - path: main\.go
      linters:
        - gochecknoinits

    - path: ^pkg/
      linters:
        - '*'

    - text: 'weak cryptographic primitive'
      linters:
        - gosec

    - text: 'G104:'
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info
