name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'front/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'front/**'

jobs:
  quality-check:
    name: Quality Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./front
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: TypeScript type check
      run: npm run type-check

    - name: ESLint check
      run: npm run lint

    - name: Run tests with coverage
      run: npm run test:ci

    - name: Build application
      run: npm run build

    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: front/coverage/
        retention-days: 7